# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181101_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
