# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rental_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
